// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://otssdmzghjbeqntvuxgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90c3NkbXpnaGpiZXFudHZ1eGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTgxNzAsImV4cCI6MjA4ODY3NDE3MH0.xuaPh_rGdQXggQAAblD-RolGGGolvrbBOOSDf5kscM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
